In [1]:
import requests
import pandas as pd

# HGNC

In [ ]:
# Download HGNC dataset
'''url = "https://storage.googleapis.com/public-download-files/hgnc/tsv/tsv/hgnc_complete_set.txt"
output_file = "hgnc_complete_set.txt"

response = requests.get(url)
if response.status_code == 200:
    with open(output_file, "wb") as f:
        f.write(response.content)
    print("Download successful!")
else:
    print(f"Failed to download. Status code: {response.status_code}")'''

In [2]:
from collections import defaultdict

# Load HGNC file
hgnc_df = pd.read_csv("hgnc_complete_set.txt", sep="\t", dtype=str).fillna("")

# Final mapping: name/synonym → list of UniProt IDs
hgnc_to_uniprot = defaultdict(list)

for _, row in hgnc_df.iterrows():
    uniprot_ids = row['uniprot_ids'].split('|') if row['uniprot_ids'] else []
    if not uniprot_ids:
        continue

    # 1. HGNC ID
    hgnc_id = row['hgnc_id']
    if hgnc_id:
        hgnc_to_uniprot[hgnc_id].extend(uniprot_ids)

    # 2. Approved Symbol
    approved_symbol = row['symbol']
    if approved_symbol:
        hgnc_to_uniprot[approved_symbol].extend(uniprot_ids)

    # 3. Approved Name
    approved_name = row['name']
    if approved_name:
        hgnc_to_uniprot[approved_name].extend(uniprot_ids)

    # 4. Approved entrez_id
    approved_name = row['entrez_id']
    if approved_name:
        hgnc_to_uniprot[approved_name].extend(uniprot_ids)

    # 5. Approved ensembl_gene_id
    approved_name = row['ensembl_gene_id']
    if approved_name:
        hgnc_to_uniprot[approved_name].extend(uniprot_ids)

    # 6. Approved vega_id
    approved_name = row['vega_id']
    if approved_name:
        hgnc_to_uniprot[approved_name].extend(uniprot_ids)

    # 7. Approved ucsc_id
    approved_name = row['ucsc_id']
    if approved_name:
        hgnc_to_uniprot[approved_name].extend(uniprot_ids)

    # 8. Approved ena
    approved_name = row['ena']
    if approved_name:
        hgnc_to_uniprot[approved_name].extend(uniprot_ids)

    # 9. Approved ccds_id
    approved_name = row['ccds_id']
    if approved_name:
        hgnc_to_uniprot[approved_name].extend(uniprot_ids)

    # 10. Approved uniprot_ids
    approved_name = row['uniprot_ids']
    if approved_name:
        hgnc_to_uniprot[approved_name].extend(uniprot_ids)

     # 11. Approved mgd_id
    approved_name = row['mgd_id']
    if approved_name:
        hgnc_to_uniprot[approved_name].extend(uniprot_ids)

    # 12. Approved omim_id
    approved_name = row['omim_id']
    if approved_name:
        hgnc_to_uniprot[approved_name].extend(uniprot_ids)

    # 13. Approved mirbase
    approved_name = row['mirbase']
    if approved_name:
        hgnc_to_uniprot[approved_name].extend(uniprot_ids)
    
    # 14. Approved alias_symbol
    approved_name = row['alias_symbol']
    if approved_name:
        hgnc_to_uniprot[approved_name].extend(uniprot_ids)
    
    # 15. Approved alias_name
    approved_name = row['alias_name']
    if approved_name:
        hgnc_to_uniprot[approved_name].extend(uniprot_ids)

     # 16. Approved prev_symbol
    approved_name = row['prev_symbol']
    if approved_name:
        hgnc_to_uniprot[approved_name].extend(uniprot_ids)

    # 17. Approved prev_name
    approved_name = row['prev_name']
    if approved_name:
        hgnc_to_uniprot[approved_name].extend(uniprot_ids)

    # 18. Approved refseq_accession
    approved_name = row['refseq_accession']
    if approved_name:
        hgnc_to_uniprot[approved_name].extend(uniprot_ids)
# Optional: Remove duplicates from values
for key in hgnc_to_uniprot:
    hgnc_to_uniprot[key] = sorted(set(hgnc_to_uniprot[key]))

In [3]:
len(hgnc_to_uniprot)

289440

In [ ]:
# hgnc_to_uniprot

# KEGG

In [ ]:
'''# Step 1: Download the mapping data
url = "https://rest.kegg.jp/conv/uniprot/hsa"
response = requests.get(url)
response.raise_for_status()  # Raise an error if the request failed

# Step 2: Parse the data
lines = response.text.strip().split('\n')
data = []

for line in lines:
    kegg_id, uniprot_id = line.split('\t')
    uniprot_id = uniprot_id.replace("up:", "")
    data.append((kegg_id, uniprot_id))

# Step 3: Save as CSV
df = pd.DataFrame(data, columns=["KEGG_ID", "UniProt_ID"])
df.to_csv("kegg_uniprot_mapping.csv", index=False)

print("CSV file saved as 'kegg_uniprot_mapping.csv'")'''

In [ ]:
#kegg_df = pd.read_csv("kegg_uniprot_mapping.csv")
#kegg_df

In [ ]:
# Group by KEGG_ID and aggregate UniProt_IDs into sets
#kegg_to_uniprot = kegg_df.groupby("KEGG_ID")["UniProt_ID"].apply(set).to_dict()
#kegg_to_uniprot

In [ ]:
#kegg_to_uniprot

# Uniprot

In [ ]:
'''# Load the extracted .tab file
df = pd.read_csv("HUMAN_9606_idmapping.dat", sep="\t", header=None, names=["UniProt_ID", "Database", "Value"])

# Group by UniProt_ID and Database, and aggregate multiple mappings with ';'
pivot_df = df.groupby(["UniProt_ID", "Database"])["Value"] \
             .apply(lambda x: ";".join(sorted(set(x)))) \
             .unstack(fill_value="")  # Convert 'Database' values into columns

# Optional: Save to file
pivot_df.to_csv("uniprot_human_mappings_wide.csv")

# Preview
pivot_df'''

In [4]:
pivot_df = pd.read_csv("uniprot_human_mappings_wide.csv")
pivot_df

C:\Users\aycan\AppData\Local\Temp\ipykernel_18212\1551780315.py:1: DtypeWarning: Columns (1,2,3,4,5,6,8,9,10,11,12,13,14,15,18,19,20,21,22,24,25,26,27,28,29,30,31,32,33,35,36,37,38,39,40,41,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,62,67,68,69) have mixed types. Specify dtype option on import or set low_memory=False.
  pivot_df = pd.read_csv("uniprot_human_mappings_wide.csv")

,UniProt_ID,Allergome,BioCyc,BioGRID,BioMuta,CCDS,CPTAC,CRC64,ChEMBL,ChiTaRS,...,UCSC,UniParc,UniPathway,UniProtKB-ID,UniRef100,UniRef50,UniRef90,VEuPathDB,eggNOG,neXtProt
0,A0A023HJ61,NaN,NaN,NaN,NaN,NaN,NaN,AAF8A92628F79317,NaN,RAB4A,...,NaN,UPI00045657B6,NaN,A0A023HJ61_HUMAN,UniRef100_A0A023HJ61,UniRef50_A0A5F4VY60,UniRef90_A0A4W2CIY0,NaN,NaN,NaN
1,A0A023HN28,NaN,NaN,NaN,NaN,NaN,NaN,B91052A58E17BA3E,NaN,NaN,...,NaN,UPI00004CCEE0,NaN,A0A023HN28_HUMAN,UniRef100_P35125,UniRef50_P35125,UniRef90_P35125,NaN,NaN,NaN
2,A0A023I7F4,NaN,NaN,NaN,NaN,NaN,NaN,E68E0901AA07F046,NaN,CYTB,...,NaN,UPI0004562ED2,NaN,A0A023I7F4_HUMAN,UniRef100_A0A023I7F4,UniRef50_P00156,UniRef90_P00156,NaN,NaN,NaN
3,A0A023I7H2,NaN,NaN,NaN,NaN,NaN,NaN,7FEF2C5032E0A722,NaN,MT-ND5,...,NaN,UPI000456287E,NaN,A0A023I7H2_HUMAN,UniRef100_A0A023I7H2,UniRef50_P03915,UniRef90_P03915,NaN,NaN,NaN
4,A0A023I7H5,NaN,NaN,NaN,NaN,NaN,NaN,9711FB0E97E44EF9,NaN,ATP6,...,NaN,UPI00045635B7,NaN,A0A023I7H5_HUMAN,UniRef100_A0A023I7H5,UniRef50_P00846,UniRef90_P00846,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237990,X6RLX0,NaN,NaN,NaN,NaN,NaN,NaN,E66981F91E9E9586,NaN,ERC1,...,uc058jrc.1,UPI0002841219,NaN,X6RLX0_HUMAN,UniRef100_X6RLX0,UniRef50_Q8IUD2,UniRef90_Q8IUD2,HostDB:ENSG00000082805,NaN,NaN
237991,X6RLY7,NaN,NaN,NaN,NaN,NaN,NaN,18001210F3B79593,NaN,CACNA2D4,...,uc058jsw.1,UPI0002841222,NaN,X6RLY7_HUMAN,UniRef100_Q7Z3S7,UniRef50_Q7Z3S7,UniRef90_Q7Z3S7,HostDB:ENSG00000151062,NaN,NaN
237992,X6RM00,NaN,NaN,NaN,NaN,NaN,NaN,EE926DACD351A86E,NaN,ERC1,...,uc058jrb.1,UPI000284121A,NaN,X6RM00_HUMAN,UniRef100_X6RM00,UniRef50_Q8IUD2,UniRef90_Q8IUD2,HostDB:ENSG00000082805,NaN,NaN
237993,X6RM24,NaN,NaN,NaN,NaN,NaN,NaN,1BF427FAC131C597,NaN,ENOSF1,...,uc060mtr.1,UPI0002B83339,NaN,X6RM24_HUMAN,UniRef100_X6RM24,UniRef50_Q7L5Y1-3,UniRef90_Q7L5Y1-3,HostDB:ENSG00000132199,NaN,NaN
237994,X6RM59,NaN,NaN,NaN,NaN,NaN,NaN,8F7C6BE1590FFD54,NaN,NT5C3A,...,uc064cri.1,UPI0000378302,NaN,X6RM59_HUMAN,UniRef100_Q9H0P0,UniRef50_Q9H0P0,UniRef90_Q9H0P0,HostDB:ENSG00000122643,NaN,NaN

In [ ]:
pivot_df.columns

In [5]:
pivot_df['UniProtKB-ID'] = pivot_df['UniProtKB-ID'].str.replace('_HUMAN$', '', regex=True)
pivot_df

,UniProt_ID,Allergome,BioCyc,BioGRID,BioMuta,CCDS,CPTAC,CRC64,ChEMBL,ChiTaRS,...,UCSC,UniParc,UniPathway,UniProtKB-ID,UniRef100,UniRef50,UniRef90,VEuPathDB,eggNOG,neXtProt
0,A0A023HJ61,NaN,NaN,NaN,NaN,NaN,NaN,AAF8A92628F79317,NaN,RAB4A,...,NaN,UPI00045657B6,NaN,A0A023HJ61,UniRef100_A0A023HJ61,UniRef50_A0A5F4VY60,UniRef90_A0A4W2CIY0,NaN,NaN,NaN
1,A0A023HN28,NaN,NaN,NaN,NaN,NaN,NaN,B91052A58E17BA3E,NaN,NaN,...,NaN,UPI00004CCEE0,NaN,A0A023HN28,UniRef100_P35125,UniRef50_P35125,UniRef90_P35125,NaN,NaN,NaN
2,A0A023I7F4,NaN,NaN,NaN,NaN,NaN,NaN,E68E0901AA07F046,NaN,CYTB,...,NaN,UPI0004562ED2,NaN,A0A023I7F4,UniRef100_A0A023I7F4,UniRef50_P00156,UniRef90_P00156,NaN,NaN,NaN
3,A0A023I7H2,NaN,NaN,NaN,NaN,NaN,NaN,7FEF2C5032E0A722,NaN,MT-ND5,...,NaN,UPI000456287E,NaN,A0A023I7H2,UniRef100_A0A023I7H2,UniRef50_P03915,UniRef90_P03915,NaN,NaN,NaN
4,A0A023I7H5,NaN,NaN,NaN,NaN,NaN,NaN,9711FB0E97E44EF9,NaN,ATP6,...,NaN,UPI00045635B7,NaN,A0A023I7H5,UniRef100_A0A023I7H5,UniRef50_P00846,UniRef90_P00846,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
237990,X6RLX0,NaN,NaN,NaN,NaN,NaN,NaN,E66981F91E9E9586,NaN,ERC1,...,uc058jrc.1,UPI0002841219,NaN,X6RLX0,UniRef100_X6RLX0,UniRef50_Q8IUD2,UniRef90_Q8IUD2,HostDB:ENSG00000082805,NaN,NaN
237991,X6RLY7,NaN,NaN,NaN,NaN,NaN,NaN,18001210F3B79593,NaN,CACNA2D4,...,uc058jsw.1,UPI0002841222,NaN,X6RLY7,UniRef100_Q7Z3S7,UniRef50_Q7Z3S7,UniRef90_Q7Z3S7,HostDB:ENSG00000151062,NaN,NaN
237992,X6RM00,NaN,NaN,NaN,NaN,NaN,NaN,EE926DACD351A86E,NaN,ERC1,...,uc058jrb.1,UPI000284121A,NaN,X6RM00,UniRef100_X6RM00,UniRef50_Q8IUD2,UniRef90_Q8IUD2,HostDB:ENSG00000082805,NaN,NaN
237993,X6RM24,NaN,NaN,NaN,NaN,NaN,NaN,1BF427FAC131C597,NaN,ENOSF1,...,uc060mtr.1,UPI0002B83339,NaN,X6RM24,UniRef100_X6RM24,UniRef50_Q7L5Y1-3,UniRef90_Q7L5Y1-3,HostDB:ENSG00000132199,NaN,NaN
237994,X6RM59,NaN,NaN,NaN,NaN,NaN,NaN,8F7C6BE1590FFD54,NaN,NT5C3A,...,uc064cri.1,UPI0000378302,NaN,X6RM59,UniRef100_Q9H0P0,UniRef50_Q9H0P0,UniRef90_Q9H0P0,HostDB:ENSG00000122643,NaN,NaN

In [6]:
'''filtered_pivot = pivot_df[['UniProt_ID','Gene_Name', 'CCDS', 'Ensembl','GeneID', 'KEGG', 'HGNC', 'VEuPathDB',  
                           'Gene_Synonym', 'ChiTaRS', 'RefSeq', 'UniProtKB-ID', 'GeneTree', 'DrugBank', 'ChEMBL', 
                           'BioMuta', 'OMA']]'''
filtered_pivot = pivot_df[['UniProt_ID','Gene_Name','Ensembl','KEGG', 'HGNC','UniProtKB-ID', 'STRING','GeneID', 
                           'Gene_Synonym', 'Gene_ORFName', 'GeneCards']]
filtered_pivot

,UniProt_ID,Gene_Name,Ensembl,KEGG,HGNC,UniProtKB-ID,STRING,GeneID,Gene_Synonym,Gene_ORFName,GeneCards
0,A0A023HJ61,RAB4A,NaN,NaN,NaN,A0A023HJ61,NaN,NaN,NaN,NaN,NaN
1,A0A023HN28,NaN,NaN,NaN,NaN,A0A023HN28,NaN,NaN,NaN,NaN,NaN
2,A0A023I7F4,CYTB,NaN,NaN,NaN,A0A023I7F4,NaN,NaN,NaN,NaN,NaN
3,A0A023I7H2,ND5,NaN,NaN,NaN,A0A023I7H2,NaN,NaN,NaN,NaN,NaN
4,A0A023I7H5,ATP6,NaN,NaN,NaN,A0A023I7H5,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
237990,X6RLX0,ERC1,ENSG00000082805.21,NaN,HGNC:17072,X6RLX0,NaN,23085.0,NaN,NaN,NaN
237991,X6RLY7,CACNA2D4,ENSG00000151062.15;ENSG00000284953.2,NaN,HGNC:20202,X6RLY7,NaN,NaN,NaN,NaN,NaN
237992,X6RM00,ERC1,ENSG00000082805.21,NaN,HGNC:17072,X6RM00,NaN,23085.0,NaN,NaN,NaN
237993,X6RM24,ENOSF1,ENSG00000132199.20,NaN,HGNC:30365,X6RM24,NaN,NaN,NaN,NaN,NaN
237994,X6RM59,NT5C3A,ENSG00000122643.24,NaN,HGNC:17820,X6RM59,NaN,51251.0,NaN,NaN,NaN

In [8]:
value_to_uniprot = {}
for column in filtered_pivot.columns:
    if column == 'UniProt_ID':
        continue  # skip the 'UniProt_ID' column itself

    # Only keep rows where this column is not NaN
    non_empty = filtered_pivot.loc[filtered_pivot[column].notna(), ['UniProt_ID', column]]

    for _, row in non_empty.iterrows():
        uniprot_id = row['UniProt_ID']
        ext_ids = str(row[column]).split(';')

        # Add mapping: ext_id → uniprot_id
        for ext_id in ext_ids:
            ext_id = ext_id.strip()
            if not ext_id:
                continue
            if ext_id in value_to_uniprot:
                value_to_uniprot[ext_id].add(uniprot_id)
            else:
                value_to_uniprot[ext_id] = {uniprot_id}

        # Add self-mapping: uniprot_id → uniprot_id
        if uniprot_id in value_to_uniprot:
            value_to_uniprot[uniprot_id].add(uniprot_id)
        else:
            value_to_uniprot[uniprot_id] = {uniprot_id}         
#value_to_uniprot

In [9]:
len(value_to_uniprot)

373986

In [10]:
count = 0
for key, val in value_to_uniprot.items() :
    if key in ['CYTB', 'ND5', 'ATP6', 'ND2'] :
        continue
    if count < 6 :
        count += 1
        print(f"{key} : {val}")
    else : break

RAB4A : {'P20338', 'A0A087WYT5', 'A0A023HJ61'}
A0A023HJ61 : {'A0A023HJ61'}
A0A023I7F4 : {'A0A023I7F4'}
A0A023I7H2 : {'A0A023I7H2'}
A0A023I7H5 : {'A0A023I7H5'}
A0A023I7J4 : {'A0A023I7J4'}

In [11]:
# Merge KEGG-HGNC-UniProt Dictionaries
# hgnc_to_uniprot + kegg_to_uniprot + value_to_uniprot
from collections import defaultdict
import json

# Initialize merged dictionary with default value as empty set
merged_dict = defaultdict(set)

# List of dictionaries to merge
#all_dicts = [hgnc_to_uniprot, kegg_to_uniprot, value_to_uniprot]
all_dicts = [hgnc_to_uniprot, value_to_uniprot]
# Merge them
for d in all_dicts:
    for k, v in d.items():
        merged_dict[k].update(v)

In [12]:
len(merged_dict)

575641

In [13]:
# Convert sets to lists since JSON does not support sets
json_ready_dict = {k: list(v) for k, v in merged_dict.items()}

# Save to JSON file
with open("uniprot_synonym_mapping.json", "w", encoding="utf-8") as f:
    json.dump(json_ready_dict, f, indent=2)