# Recon3D Upstream and Downstream Metabolites

In [2]:
import os
import cobra

from cobra import Model, Reaction, Metabolite
from cobra.io import load_json_model

In [3]:
recon3d_path = os.path.join("datasets", "network_models", "Recon3D.json")  # JSON model

recon3d = load_json_model(recon3d_path)
recon3d

In [3]:
print(f"Recon3D has {len(recon3d.reactions)} reactions.")
print(f"Recon3D has {len(recon3d.metabolites)} metabolites.")

Recon3D has 10600 reactions.
Recon3D has 5835 metabolites.

In [4]:
recon3d.metabolites

[<Metabolite 10fthf_c at 0x1201c289c10>,
 <Metabolite 10fthf_l at 0x1203e46a8e0>,
 <Metabolite 10fthf_m at 0x1203e46a880>,
 <Metabolite 11docrtsl_c at 0x1203e46a730>,
 <Metabolite 11docrtsl_m at 0x1203e46a940>,
 <Metabolite 11docrtsl_r at 0x1203e46abe0>,
 <Metabolite 11docrtstrn_c at 0x1203e46abb0>,
 <Metabolite 11docrtstrn_m at 0x1203e46a970>,
 <Metabolite 11docrtstrn_r at 0x1203e46aa00>,
 <Metabolite 13dampp_c at 0x1203e46a8b0>,
 <Metabolite h2o_c at 0x1203e46a9d0>,
 <Metabolite o2_c at 0x1203e46aa90>,
 <Metabolite bamppald_c at 0x1203e46a9a0>,
 <Metabolite 34hpl_m at 0x1203e46aa30>,
 <Metabolite 10fthf5glu_c at 0x1203e46ab80>,
 <Metabolite h2o2_c at 0x1203e46aac0>,
 <Metabolite 10fthf5glu_l at 0x1203e46aa60>,
 <Metabolite nh4_c at 0x1203e46ac10>,
 <Metabolite h2o_m at 0x1203e46ac40>,
 <Metabolite 10fthf5glu_m at 0x1203e46ac70>,
 <Metabolite 10fthf6glu_c at 0x1203e46aca0>,
 <Metabolite o2_m at 0x1203e46acd0>,
 <Metabolite 10fthf6glu_l at 0x1203e46ad00>,
 <Metabolite 10fthf6glu_m at 0x1203e46ad30>,
 <Metabolite 2425dhvitd2_m at 0x1203e46ad60>,
 <Metabolite 10fthf7glu_c at 0x1203e46ad90>,
 <Metabolite 10fthf7glu_l at 0x1203e46adc0>,
 <Metabolite co2_c at 0x1203e46adf0>,
 <Metabolite h_m at 0x1203e46ae20>,
 <Metabolite 10fthf7glu_m at 0x1203e46ae50>,
 <Metabolite nadph_m at 0x1203e46ae80>,
 <Metabolite 1a2425thvitd2_m at 0x1203e46aeb0>,
 <Metabolite nadp_m at 0x1203e46aee0>,
 <Metabolite 2425dhvitd3_m at 0x1203e46af10>,
 <Metabolite 1a25dhvitd2_m at 0x1203e46af40>,
 <Metabolite 1a25dhvitd3_m at 0x1203e46af70>,
 <Metabolite 34hpp_c at 0x1203e46afa0>,
 <Metabolite h_c at 0x1203e46afd0>,
 <Metabolite srtn_c at 0x1203bb38040>,
 <Metabolite 1mncam_c at 0x1203bb38070>,
 <Metabolite 1mncam_e at 0x1203bb380a0>,
 <Metabolite atp_c at 0x1203bb380d0>,
 <Metabolite hgentis_c at 0x1203bb38100>,
 <Metabolite adp_c at 0x1203bb38130>,
 <Metabolite 5homeprazole_e at 0x1203bb38160>,
 <Metabolite pi_c at 0x1203bb38190>,
 <Metabolite 5homeprazole_c at 0x1203bb381c0>,
 <Metabolite 5hoxindact_c at 0x1203bb381f0>,
 <Metabolite 35cgmp_c at 0x1203bb38220>,
 <Metabolite h_x at 0x1203bb38250>,
 <Metabolite 35cgmp_n at 0x1203bb38280>,
 <Metabolite 5hoxindoa_c at 0x1203bb382b0>,
 <Metabolite 5htrp_e at 0x1203bb382e0>,
 <Metabolite 1pipdn2c_x at 0x1203bb38310>,
 <Metabolite 3aib_m at 0x1203bb38340>,
 <Metabolite nadh_x at 0x1203bb38370>,
 <Metabolite 2mop_m at 0x1203bb383a0>,
 <Metabolite 5mthf_e at 0x1203bb383d0>,
 <Metabolite Lpipecol_x at 0x1203bb38400>,
 <Metabolite nad_x at 0x1203bb38430>,
 <Metabolite 5mthf_c at 0x1203bb38460>,
 <Metabolite 2425dhvitd2_c at 0x1203bb38490>,
 <Metabolite 5thf_c at 0x1203bb384c0>,
 <Metabolite 2425dhvitd2_e at 0x1203bb384f0>,
 <Metabolite 5thf_l at 0x1203bb38520>,
 <Metabolite glu__L_m at 0x1203bb38550>,
 <Metabolite 2425dhvitd3_c at 0x1203bb38580>,
 <Metabolite 5thf_m at 0x1203bb385b0>,
 <Metabolite 2425dhvitd3_e at 0x1203bb385e0>,
 <Metabolite 6dhf_c at 0x1203bb38610>,
 <Metabolite 25hvitd2_m at 0x1203bb38640>,
 <Metabolite 6dhf_l at 0x1203bb38670>,
 <Metabolite 3aib_c at 0x1203bb386a0>,
 <Metabolite 6dhf_m at 0x1203bb386d0>,
 <Metabolite 25hvitd3_m at 0x1203bb38700>,
 <Metabolite 6htststerone_c at 0x1203bb38730>,
 <Metabolite 24nph_e at 0x1203bb38760>,
 <Metabolite 6htststerone_e at 0x1203bb38790>,
 <Metabolite 3dphb_m at 0x1203bb387c0>,
 <Metabolite 24nph_c at 0x1203bb387f0>,
 <Metabolite 25hvitd2_c at 0x1203bb38820>,
 <Metabolite 3dpdhb_m at 0x1203bb38850>,
 <Metabolite 6htststerone_r at 0x1203bb38880>,
 <Metabolite 25hvitd2_e at 0x1203bb388b0>,
 <Metabolite 6thf_c at 0x1203bb388e0>,
 <Metabolite 3dsphgn_c at 0x1203bb38910>,
 <Metabolite 25hvitd3_c at 0x1203bb38940>,
 <Metabolite 6thf_l at 0x1203bb38970>,
 <Metabolite 6thf_m at 0x1203bb389a0>,
 <Metabolite 25hvitd3_e at 0x1203bb389d0>,
 <Metabolite 7dhchsterol_r at 0x1203bb38a00>,
 <Metabolite sphgn_c at 0x1203bb38a30>,
 <Metabolite 2amac_c at 0x1203bb38a60>,
 <Metabolite 7dhchsterol_c at 0x1203bb38a90>,
 <Metabolite pyr_c at 0x1203bb38ac0>,
 <Metabolite 7dhf_c at 0x1203bb38af0>,
 <Metabolite 3hanthrn_c at 0x1203bb38b20>,
 <Metabolite cmusa_c at 0x1203bb38b50>,
 <Metabolite 7dhf_l at 0x1203bb38b80>,
 <Metabolite 7dhf_m at 0x1203bb38bb0>,
 <Metabolite 7thf_c at 0x1203bb38be0>,
 <Metabolite 7thf_l at 0x1203bb38c10>,
 <Metabolite 7thf_m at 0x1203bb38c40>,
 <Metabolite b2coa_m at 0x1203bb38c70>,
 <Metabolite nadph_c at 0x1203bb38ca0>,
 <Metabolite nadp_c at 0x1203bb38cd0>,
 <Metabolite 3hbcoa__R_m at 0x1203bb38d00>,
 <Metabolite paps_c at 0x1203bb38d30>,
 <Metabolite man_c at 0x1203bb38d60>,
 <Metabolite Lcyst_c at 0x1203bb38d90>,
 <Metabolite 3hibutcoa_m at 0x1203bb38dc0>,
 <Metabolite pap_c at 0x1203bb38df0>,
 <Metabolite 3hmp_m at 0x1203bb38e20>,
 <Metabolite m2mn_l at 0x1203bb38e50>,
 <Metabolite L2aadp_c at 0x1203bb38e80>,
 <Metabolite glu__L_c at 0x1203bb38eb0>,
 <Metabolite L2aadp_m at 0x1203bb38ee0>,
 <Metabolite hLkynr_c at 0x1203bb38f10>,
 <Metabolite man_l at 0x1203bb38f40>,
 <Metabolite akg_m at 0x1203bb38f70>,
 <Metabolite akg_c at 0x1203bb38fa0>,
 <Metabolite 42A3HP24DB_c at 0x1203bb38fd0>,
 <Metabolite mn_l at 0x1203bb42040>,
 <Metabolite 2dr1p_c at 0x1203bb42070>,
 <Metabolite drib_c at 0x1203bb420a0>,
 <Metabolite nadh_c at 0x1203bb420d0>,
 <Metabolite dopa_c at 0x1203bb42100>,
 <Metabolite nad_c at 0x1203bb42130>,
 <Metabolite galgluside_hs_c at 0x1203bb42160>,
 <Metabolite 2hb_c at 0x1203bb42190>,
 <Metabolite 2obut_c at 0x1203bb421c0>,
 <Metabolite coa_c at 0x1203bb421f0>,
 <Metabolite h_e at 0x1203bb42220>,
 <Metabolite 3hpp_c at 0x1203bb42250>,
 <Metabolite udpgal_c at 0x1203bb42280>,
 <Metabolite 2hb_e at 0x1203bb422b0>,
 <Metabolite thcrm_hs_c at 0x1203bb422e0>,
 <Metabolite 3mox4hpac_c at 0x1203bb42310>,
 <Metabolite hco3_e at 0x1203bb42340>,
 <Metabolite 3mlda_c at 0x1203bb42370>,
 <Metabolite udp_c at 0x1203bb423a0>,
 <Metabolite hco3_c at 0x1203bb423d0>,
 <Metabolite 3mlda_e at 0x1203bb42400>,
 <Metabolite na1_e at 0x1203bb42430>,
 <Metabolite 3mob_c at 0x1203bb42460>,
 <Metabolite h_g at 0x1203bb42490>,
 <Metabolite galgluside_hs_g at 0x1203bb424c0>,
 <Metabolite na1_c at 0x1203bb424f0>,
 <Metabolite 3mob_m at 0x1203bb42520>,
 <Metabolite 3mop_c at 0x1203bb42550>,
 <Metabolite 2mcit_c at 0x1203bb42580>,
 <Metabolite 3mop_m at 0x1203bb425b0>,
 <Metabolite 2mcit_e at 0x1203bb425e0>,
 <Metabolite 3m4hpga_c at 0x1203bb42610>,
 <Metabolite udpgal_g at 0x1203bb42640>,
 <Metabolite nadh_m at 0x1203bb42670>,
 <Metabolite thcrm_hs_g at 0x1203bb426a0>,
 <Metabolite 3mox4hoxm_c at 0x1203bb426d0>,
 <Metabolite nad_m at 0x1203bb42700>,
 <Metabolite 3moxtyr_c at 0x1203bb42730>,
 <Metabolite udp_g at 0x1203bb42760>,
 <Metabolite 2oxoadp_m at 0x1203bb42790>,
 <Metabolite h2o_l at 0x1203bb427c0>,
 <Metabolite coa_m at 0x1203bb427f0>,
 <Metabolite T_antigen_g at 0x1203bb42820>,
 <Metabolite co2_m at 0x1203bb42850>,
 <Metabolite pi_l at 0x1203bb42880>,
 <Metabolite glutcoa_m at 0x1203bb428b0>,
 <Metabolite 2oxoadp_c at 0x1203bb428e0>,
 <Metabolite uacgam_g at 0x1203bb42910>,
 <Metabolite adn_l at 0x1203bb42940>,
 <Metabolite 34dhmald_c at 0x1203bb42970>,
 <Metabolite gncore1_g at 0x1203bb429a0>,
 <Metabolite 34dhoxpeg_c at 0x1203bb429d0>,
 <Metabolite 3sala_m at 0x1203bb42a00>,
 <Metabolite 34dhoxpeg_e at 0x1203bb42a30>,
 <Metabolite 3sala_c at 0x1203bb42a60>,
 <Metabolite 34dhpha_c at 0x1203bb42a90>,
 <Metabolite asp__L_c at 0x1203bb42ac0>,
 <Metabolite core2_g at 0x1203bb42af0>,
 <Metabolite amet_c at 0x1203bb42b20>,
 <Metabolite gncore2_g at 0x1203bb42b50>,
 <Metabolite asp__L_m at 0x1203bb42b80>,
 <Metabolite ahcys_c at 0x1203bb42bb0>,
 <Metabolite hyptaur_c at 0x1203bb42be0>,
 <Metabolite aact_c at 0x1203bb42c10>,
 <Metabolite homoval_c at 0x1203bb42c40>,
 <Metabolite mthgxl_c at 0x1203bb42c70>,
 <Metabolite 3snpyr_c at 0x1203bb42ca0>,
 <Metabolite 34dhphe_e at 0x1203bb42cd0>,
 <Metabolite 3snpyr_m at 0x1203bb42d00>,
 <Metabolite aact_m at 0x1203bb42d30>,
 <Metabolite 34dhphe_c at 0x1203bb42d60>,
 <Metabolite 34dhpac_c at 0x1203bb42d90>,
 <Metabolite L2aadp6sa_m at 0x1203bb42dc0>,
 <Metabolite 34dhoxmand_c at 0x1203bb42df0>,
 <Metabolite fucgalacglcgalgluside_hs_g at 0x1203bb42e20>,
 <Metabolite 34hpp_m at 0x1203bb42e50>,
 <Metabolite ttccoa_x at 0x1203bb42e80>,
 <Metabolite udpacgal_g at 0x1203bb42eb0>,
 <Metabolite acac_x at 0x1203bb42ee0>,
 <Metabolite acald_m at 0x1203bb42f10>,
 <Metabolite acgalfucgalacglcgalgluside_hs_g at 0x1203bb42f40>,
 <Metabolite acald_c at 0x1203bb42f70>,
 <Metabolite acald_r at 0x1203bb42fa0>,
 <Metabolite galfucgalacglcgalgluside_hs_g at 0x1203bb42fd0>,
 <Metabolite acald_x at 0x1203bb4b040>,
 <Metabolite fuc12gal14acglcgalgluside_hs_g at 0x1203bb4b070>,
 <Metabolite atp_m at 0x1203bb4b0a0>,
 <Metabolite galfuc12gal14acglcgalgluside_hs_g at 0x1203bb4b0d0>,
 <Metabolite adp_m at 0x1203bb4b100>,
 <Metabolite acgalfuc12gal14acglcgalgluside_hs_g at 0x1203bb4b130>,
 <Metabolite pi_m at 0x1203bb4b160>,
 <Metabolite fucgalacgalfuc12gal14acglcgalgluside_hs_g at 0x1203bb4b190>,
 <Metabolite hco3_m at 0x1203bb4b1c0>,
 <Metabolite acgalfucgalacgalfuc12gal14acglcgalgluside_hs_g at 0x1203bb4b1f0>,
 <Metabolite malcoa_m at 0x1203bb4b220>,
 <Metabolite accoa_c at 0x1203bb4b250>,
 <Metabolite fucgalacglcgal14acglcgalgluside_hs_g at 0x1203bb4b280>,
 <Metabolite acgalfucgalacglcgal14acglcgalgluside_hs_g at 0x1203bb4b2b0>,
 <Metabolite accoa_g at 0x1203bb4b2e0>,
 <Metabolite fucgalacgalfucgalacglcgal14acglcgalgluside_hs_g at 0x1203bb4b310>,
 <Metabolite amp_m at 0x1203bb4b340>,
 <Metabolite acgalfucgalacgalfucgalacglcgal14acglcgalgluside_hs_g at 0x1203bb4b370>,
 <Metabolite ppi_m at 0x1203bb4b3a0>,
 <Metabolite galfucgalacglcgal14acglcgalgluside_hs_g at 0x1203bb4b3d0>,
 <Metabolite ppa_m at 0x1203bb4b400>,
 <Metabolite fucfucgalacglcgalacglcgal14acglcgalgluside_hs_g at 0x1203bb4b430>,
 <Metabolite galgalfucfucgalacglcgalacglcgal14acglcgalgluside_hs_g at 0x1203bb4b460>,
 <Metabolite accoa_n at 0x1203bb4b490>,
 <Metabolite accoa_r at 0x1203bb4b4c0>,
 <Metabolite sucsal_m at 0x1203bb4b4f0>,
 <Metabolite acetone_e at 0x1203bb4b520>,
 <Metabolite acetone_c at 0x1203bb4b550>,
 <Metabolite acetone_m at 0x1203bb4b580>,
 <Metabolite acgagbside_hs_c at 0x1203bb4b5b0>,
 <Metabolite acgagbside_hs_g at 0x1203bb4b5e0>,
 <Metabolite acgagbside_hs_l at 0x1203bb4b610>,
 <Metabolite so3_c at 0x1203bb4b640>,
 <Metabolite acgalfucgalacgalfuc12gal14acglcgalgluside_hs_e at 0x1203bb4b670>,
 <Metabolite acgalfucgalacgalfuc12gal14acglcgalgluside_hs_c at 0x1203bb4b6a0>,
 <Metabolite pyr_m at 0x1203bb4b6d0>,
 <Metabolite acgalfucgalacgalfucgalacglcgal14acglcgalgluside_hs_e at 0x1203bb4b700>,
 <Metabolite acgalfucgalacgalfucgalacglcgal14acglcgalgluside_hs_c at 0x1203bb4b730>,
 <Metabolite so3_m at 0x1203bb4b760>,
 <Metabolite acgal_c at 0x1203bb4b790>,
 <Metabolite adrnl_c at 0x1203bb4b7c0>,
 <Metabolite acgal1p_c at 0x1203bb4b7f0>,
 <Metabolite itp_c at 0x1203bb4b820>,
 <Metabolite mma_c at 0x1203bb4b850>,
 <Metabolite idp_c at 0x1203bb4b880>,
 <Metabolite nrpphr_c at 0x1203bb4b8b0>,
 <Metabolite acgal_g at 0x1203bb4b8e0>,
 <Metabolite acgal_l at 0x1203bb4b910>,
 <Metabolite gam6p_c at 0x1203bb4b940>,
 <Metabolite acgam6p_c at 0x1203bb4b970>,
 <Metabolite acgam_c at 0x1203bb4b9a0>,
 <Metabolite acgam1p_c at 0x1203bb4b9d0>,
 <Metabolite acgam_l at 0x1203bb4ba00>,
 <Metabolite 4abut_c at 0x1203bb4ba30>,
 <Metabolite abt_c at 0x1203bb4ba60>,
 <Metabolite acgbgbside_hs_c at 0x1203bb4ba90>,
 <Metabolite 4abut_m at 0x1203bb4bac0>,
 <Metabolite acgbgbside_hs_g at 0x1203bb4baf0>,
 <Metabolite coucoa_m at 0x1203bb4bb20>,
 <Metabolite xylu__L_c at 0x1203bb4bb50>,
 <Metabolite acgbgbside_hs_l at 0x1203bb4bb80>,
 <Metabolite 4hbzcoa_m at 0x1203bb4bbb0>,
 <Metabolite abt_e at 0x1203bb4bbe0>,
 <Metabolite acgpail_hs_c at 0x1203bb4bc10>,
 <Metabolite h_l at 0x1203bb4bc40>,
 <Metabolite accoa_m at 0x1203bb4bc70>,
 <Metabolite ac_c at 0x1203bb4bca0>,
 <Metabolite 4hbz_m at 0x1203bb4bcd0>,
 <Metabolite gpail_hs_c at 0x1203bb4bd00>,
 <Metabolite 4hdebrisoquine_e at 0x1203bb4bd30>,
 <Metabolite 4abut_l at 0x1203bb4bd60>,
 <Metabolite acglu_m at 0x1203bb4bd90>,
 <Metabolite 4abut_e at 0x1203bb4bdc0>,
 <Metabolite 4hdebrisoquine_c at 0x1203bb4bdf0>,
 <Metabolite ac_e at 0x1203bb4be20>,
 <Metabolite 4hglusa_m at 0x1203bb4be50>,
 <Metabolite ach_e at 0x1203bb4be80>,
 <Metabolite e4hglu_m at 0x1203bb4beb0>,
 <Metabolite 2maacoa_m at 0x1203bb4bee0>,
 <Metabolite chol_e at 0x1203bb4bf10>,
 <Metabolite ach_n at 0x1203bb4bf40>,
 <Metabolite ppcoa_m at 0x1203bb4bf70>,
 <Metabolite 4hoxpacd_c at 0x1203bb4bfa0>,
 <Metabolite ach_c at 0x1203bb4bfd0>,
 <Metabolite 4hphac_c at 0x1203bb54040>,
 <Metabolite aacoa_m at 0x1203bb54070>,
 <Metabolite coa_x at 0x1203bb540a0>,
 <Metabolite cit_c at 0x1203bb540d0>,
 <Metabolite accoa_x at 0x1203bb54100>,
 <Metabolite oaa_c at 0x1203bb54130>,
 <Metabolite acn13acngalgbside_hs_c at 0x1203bb54160>,
 <Metabolite aacoa_x at 0x1203bb54190>,
 <Metabolite acac_c at 0x1203bb541c0>,
 <Metabolite 4mop_c at 0x1203bb541f0>,
 <Metabolite acn13acngalgbside_hs_e at 0x1203bb54220>,
 <Metabolite 4mop_m at 0x1203bb54250>,
 <Metabolite acac_m at 0x1203bb54280>,
 <Metabolite acn13acngalgbside_hs_g at 0x1203bb542b0>,
 <Metabolite 3odcoa_x at 0x1203bb542e0>,
 <Metabolite 4mptnl_c at 0x1203bb54310>,
 <Metabolite 4mptnl_e at 0x1203bb54340>,
 <Metabolite acn23acngalgbside_hs_c at 0x1203bb54370>,
 <Metabolite 4mptnl_m at 0x1203bb543a0>,
 <Metabolite acn23acngalgbside_hs_e at 0x1203bb543d0>,
 <Metabolite 4mtolbutamide_e at 0x1203bb54400>,
 <Metabolite occoa_x at 0x1203bb54430>,
 <Metabolite acn23acngalgbside_hs_g at 0x1203bb54460>,
 <Metabolite 3oddcoa_x at 0x1203bb54490>,
 <Metabolite 4mtolbutamide_c at 0x1203bb544c0>,
 <Metabolite acnacngal14acglcgalgluside_hs_e at 0x1203bb544f0>,
 <Metabolite 4nphsf_e at 0x1203bb54520>,
 <Metabolite acnacngal14acglcgalgluside_hs_c at 0x1203bb54550>,
 <Metabolite 4nphsf_c at 0x1203bb54580>,
 <Metabolite dcacoa_x at 0x1203bb545b0>,
 <Metabolite acnacngal14acglcgalgluside_hs_g at 0x1203bb545e0>,
 <Metabolite 4nph_c at 0x1203bb54610>,
 <Metabolite 4nph_e at 0x1203bb54640>,
 <Metabolite acnacngalgbside_hs_c at 0x1203bb54670>,
 <Metabolite 4pyrdx_c at 0x1203bb546a0>,
 <Metabolite 3otdcoa_x at 0x1203bb546d0>,
 <Metabolite ddcacoa_x at 0x1203bb54700>,
 <Metabolite acnacngalgbside_hs_e at 0x1203bb54730>,
 <Metabolite 3ohdcoa_x at 0x1203bb54760>,
 <Metabolite 4pyrdx_e at 0x1203bb54790>,
 <Metabolite acnacngalgbside_hs_g at 0x1203bb547c0>,
 <Metabolite 5adtststeroneglc_c at 0x1203bb547f0>,
 <Metabolite tdcoa_x at 0x1203bb54820>,
 <Metabolite acmanap_c at 0x1203bb54850>,
 <Metabolite 3ohodcoa_x at 0x1203bb54880>,
 <Metabolite 5adtststeroneglc_e at 0x1203bb548b0>,
 <Metabolite pep_c at 0x1203bb548e0>,
 <Metabolite 5adtststeroneglc_r at 0x1203bb54910>,
 <Metabolite pmtcoa_x at 0x1203bb54940>,
 <Metabolite acnamp_c at 0x1203bb54970>,
 <Metabolite 3ohxccoa_x at 0x1203bb549a0>,
 <Metabolite 5adtststerones_c at 0x1203bb549d0>,
 <Metabolite 5adtststerones_e at 0x1203bb54a00>,
 <Metabolite man6p_c at 0x1203bb54a30>,
 <Metabolite 5adtststerone_c at 0x1203bb54a60>,
 <Metabolite kdnp_c at 0x1203bb54a90>,
 <Metabolite 5adtststerone_e at 0x1203bb54ac0>,
 <Metabolite 5adtststerone_r at 0x1203bb54af0>,
 <Metabolite fad_x at 0x1203bb54b20>,
 <Metabolite acnam_c at 0x1203bb54b50>,
 <Metabolite 5aop_c at 0x1203bb54b80>,
 <Metabolite acnam_l at 0x1203bb54bb0>,
 <Metabolite 5aop_m at 0x1203bb54be0>,
 <Metabolite fadh2_x at 0x1203bb54c10>,
 <Metabolite 5dhf_c at 0x1203bb54c40>,
 <Metabolite acnam_n at 0x1203bb54c70>,
 <Metabolite 5dhf_l at 0x1203bb54ca0>,
 <Metabolite acngalacglcgal14acglcgalgluside_hs_e at 0x1203bb54cd0>,
 <Metabolite dhcholoylcoa_x at 0x1203bb54d00>,
 <Metabolite acngalacglcgal14acglcgalgluside_hs_c at 0x1203bb54d30>,
 <Metabolite acngalacglcgal14acglcgalgluside_hs_g at 0x1203bb54d60>,
 <Metabolite h2o_e at 0x1203bb54d90>,
 <Metabolite acmana_c at 0x1203bb54dc0>,
 <Metabolite 5fthf_e at 0x1203bb54df0>,
 <Metabolite 2mbcoa_m at 0x1203bb54e20>,
 <Metabolite 5fthf_c at 0x1203bb54e50>,
 <Metabolite 5htrp_c at 0x1203bb54e80>,
 <Metabolite fad_m at 0x1203bb54eb0>,
 <Metabolite ahcys_r at 0x1203bb54ee0>,
 <Metabolite 2mb2coa_m at 0x1203bb54f10>,
 <Metabolite fadh2_m at 0x1203bb54f40>,
 <Metabolite n2m2nmn_l at 0x1203bb54f70>,
 <Metabolite thcholoylcoa_x at 0x1203bb54fa0>,
 <Metabolite btcoa_m at 0x1203bb54fd0>,
 <Metabolite n2m2mn_l at 0x1203bb5c040>,
 <Metabolite h2o_x at 0x1203bb5c070>,
 <Metabolite ivcoa_m at 0x1203bb5c0a0>,
 <Metabolite air_c at 0x1203bb5c0d0>,
 <Metabolite 5aizc_c at 0x1203bb5c100>,
 <Metabolite succoa_m at 0x1203bb5c130>,
 <Metabolite cholcoas_x at 0x1203bb5c160>,
 <Metabolite cholcoads_x at 0x1203bb5c190>,
 <Metabolite 3mb2coa_m at 0x1203bb5c1c0>,
 <Metabolite fmn_c at 0x1203bb5c1f0>,
 <Metabolite mal__L_c at 0x1203bb5c220>,
 <Metabolite ibcoa_m at 0x1203bb5c250>,
 <Metabolite mal__L_m at 0x1203bb5c280>,
 <Metabolite 2mp2coa_m at 0x1203bb5c2b0>,
 <Metabolite ribflv_c at 0x1203bb5c2e0>,
 <Metabolite o2_x at 0x1203bb5c310>,
 <Metabolite acrn_c at 0x1203bb5c340>,
 <Metabolite akg_e at 0x1203bb5c370>,
 <Metabolite akg_x at 0x1203bb5c3a0>,
 <Metabolite h2o2_x at 0x1203bb5c3d0>,
 <Metabolite acrn_m at 0x1203bb5c400>,
 <Metabolite hdd2coa_x at 0x1203bb5c430>,
 <Metabolite amp_c at 0x1203bb5c460>,
 <Metabolite prgstrn_c at 0x1203bb5c490>,
 <Metabolite acorn_c at 0x1203bb5c4c0>,
 <Metabolite aprgstrn_c at 0x1203bb5c4f0>,
 <Metabolite ppi_c at 0x1203bb5c520>,
 <Metabolite orn_c at 0x1203bb5c550>,
 <Metabolite ppcoa_c at 0x1203bb5c580>,
 <Metabolite cit_m at 0x1203bb5c5b0>,
 <Metabolite ppa_c at 0x1203bb5c5e0>,
 <Metabolite xol7ah_c at 0x1203bb5c610>,
 <Metabolite icit_m at 0x1203bb5c640>,
 <Metabolite ac_m at 0x1203bb5c670>,
 <Metabolite biocyt_c at 0x1203bb5c6a0>,
 <Metabolite Nacsertn_c at 0x1203bb5c6d0>,
 <Metabolite xol7ah2_c at 0x1203bb5c700>,
 <Metabolite apoC_Lys_btn_m at 0x1203bb5c730>,
 <Metabolite xoldioloneh_c at 0x1203bb5c760>,
 <Metabolite xoltriol_c at 0x1203bb5c790>,
 <Metabolite melatn_c at 0x1203bb5c7c0>,
 <Metabolite biocyt_m at 0x1203bb5c7f0>,
 <Metabolite ac_g at 0x1203bb5c820>,
 <Metabolite xol7aone_c at 0x1203bb5c850>,
 <Metabolite acetol_c at 0x1203bb5c880>,
 <Metabolite appnn_e at 0x1203bb5c8b0>,
 <Metabolite adn_c at 0x1203bb5c8e0>,
 <Metabolite xoldiolone_c at 0x1203bb5c910>,
 <Metabolite appnn_c at 0x1203bb5c940>,
 <Metabolite ala__L_e at 0x1203bb5c970>,
 <Metabolite ins_c at 0x1203bb5c9a0>,
 <Metabolite aprut_c at 0x1203bb5c9d0>,
 <Metabolite ala__L_c at 0x1203bb5ca00>,
 <Metabolite n4abutn_c at 0x1203bb5ca30>,
 <Metabolite asn__L_c at 0x1203bb5ca60>,
 <Metabolite nh4_e at 0x1203bb5ca90>,
 <Metabolite aqcobal_e at 0x1203bb5cac0>,
 <Metabolite adn_e at 0x1203bb5caf0>,
 <Metabolite asn__L_e at 0x1203bb5cb20>,
 <Metabolite aqcobal_c at 0x1203bb5cb50>,
 <Metabolite cys__L_c at 0x1203bb5cb80>,
 <Metabolite ins_e at 0x1203bb5cbb0>,
 <Metabolite arab__L_e at 0x1203bb5cbe0>,
 <Metabolite ade_e at 0x1203bb5cc10>,
 <Metabolite cys__L_e at 0x1203bb5cc40>,
 <Metabolite arab__L_c at 0x1203bb5cc70>,
 <Metabolite ala__D_e at 0x1203bb5cca0>,
 <Metabolite ade_c at 0x1203bb5ccd0>,
 <Metabolite gtp_c at 0x1203bb5cd00>,
 <Metabolite arachcoa_c at 0x1203bb5cd30>,
 <Metabolite gdp_c at 0x1203bb5cd60>,
 <Metabolite ala__D_c at 0x1203bb5cd90>,
 <Metabolite gln__L_c at 0x1203bb5cdc0>,
 <Metabolite arachcoa_x at 0x1203bb5cdf0>,
 <Metabolite gln__L_e at 0x1203bb5ce20>,
 <Metabolite gtp_m at 0x1203bb5ce50>,
 <Metabolite arachcrn_c at 0x1203bb5ce80>,
 <Metabolite gdp_m at 0x1203bb5ceb0>,
 <Metabolite gly_c at 0x1203bb5cee0>,
 <Metabolite arachcoa_m at 0x1203bb5cf10>,
 <Metabolite gly_e at 0x1203bb5cf40>,
 <Metabolite damp_c at 0x1203bb5cf70>,
 <Metabolite arachcrn_m at 0x1203bb5cfa0>,
 <Metabolite datp_c at 0x1203bb5cfd0>,
 <Metabolite ser__L_c at 0x1203bb65040>,
 <Metabolite arachdcoa_c at 0x1203bb65070>,
 <Metabolite dadp_c at 0x1203bb650a0>,
 <Metabolite arachdcoa_x at 0x1203bb650d0>,
 <Metabolite ametam_c at 0x1203bb65100>,
 <Metabolite ser__L_e at 0x1203bb65130>,
 <Metabolite arachd_e at 0x1203bb65160>,

## Metabolite : 1pyr5c_c in study ST000011.csv

In [7]:
# Get a specific metabolite from the model (e.g. 1pyr5c_c)
metabolite = recon3d.metabolites.get_by_id('1pyr5c_c')

# Get the summary of the metabolite
summary = metabolite.summary()

# # Extract the upstream and downstream metabolites from the summary
# downstream = [m for m in summary['reactions']['products']]
# upstream = [m for m in summary['reactions']['reactants']]

# print(f"{downstream = }")
# print(f"{upstream = }")

# # Print the results
# print("Downstream metabolites: ", [m.id for m in downstream])
# print("Upstream metabolites: ", [m.id for m in upstream])

SLIM OPTIMIZE PERFECT

In [8]:
metabolite

In [9]:
summary

In [10]:
summary.consuming_flux

      flux reaction  percent
P5CR   0.0     P5CR      NaN

In [11]:
summary.producing_flux

        flux reaction  percent
G5SADs   0.0   G5SADs      NaN
PRO1x    0.0    PRO1x      NaN
PROD2    0.0    PROD2      NaN

In [12]:
summary.to_frame()

       reaction  flux  factor
G5SADs   G5SADs   0.0     1.0
P5CR       P5CR   0.0    -1.0
PRO1x     PRO1x   0.0     1.0
PROD2     PROD2   0.0     1.0

In [15]:
for reaction in metabolite.reactions:
    print(reaction.metabolites)

{<Metabolite 1pyr5c_c at 0x1203bc8c0d0>: -1.0, <Metabolite h_c at 0x1203e46afd0>: -2.0, <Metabolite nadp_c at 0x1203bb38cd0>: 1.0, <Metabolite nadph_c at 0x1203bb38ca0>: -1.0, <Metabolite pro__L_c at 0x1203bc13c10>: 1.0}
{<Metabolite 1pyr5c_c at 0x1203bc8c0d0>: 1.0, <Metabolite glu5sa_c at 0x1203bc83ee0>: -1.0, <Metabolite h2o_c at 0x1203e46a9d0>: 1.0, <Metabolite h_c at 0x1203e46afd0>: 1.0}
{<Metabolite 1pyr5c_c at 0x1203bc8c0d0>: 1.0, <Metabolite h_c at 0x1203e46afd0>: 2.0, <Metabolite nad_c at 0x1203bb42130>: -1.0, <Metabolite nadh_c at 0x1203bb420d0>: 1.0, <Metabolite pro__L_c at 0x1203bc13c10>: -1.0}
{<Metabolite 1pyr5c_c at 0x1203bc8c0d0>: 1.0, <Metabolite fad_c at 0x1203bb99460>: -1.0, <Metabolite fadh2_c at 0x1203bb99520>: 1.0, <Metabolite h_c at 0x1203e46afd0>: 1.0, <Metabolite pro__L_c at 0x1203bc13c10>: -1.0}

In [ ]:
glu5sa_c